### ISSUE TITLE
removeRow and removeRows does not work.

### ISSUE THREAD

**Issue by Nick-Anderssohn** [roberthartung/google_visualization_api#12]
the member functions for DataTable removeRow and removeRows do not work.  this is the code for removeRow:

```
void removeRow(int rowIndex) {
    jsProxy.callMethod('removeRow', [removeRow]);
  }
```

should it be:

```
void removeRow(int rowIndex) {
    jsProxy.callMethod('removeRow', [rowIndex]);
  }
```

?  Same problem in removeRows.

**Comment by roberthartung** [comment]
This is fixed in version 0.2.0 -> https://pub.dartlang.org/packages/google_charts
