### ISSUE TITLE
Encounter error when using BarChart

### ISSUE THREAD

**Issue by oraclebox** [roberthartung/google_visualization_api#4]
BarChart.load().then((_) {
   chart = new BarChart(document.getElementById(containerId));
}

Exception: Uncaught Error: constructor not a function
Stack Trace:
#0      JsObject._create (dart:js:119)
#1      JsObject.JsObject (dart:js:117)
#2      Chart.Chart._ (package:google_visualization_api/charts.dart:45:68)
#3      BarChart.BarChart (package:google_visualization_api/src/charts/bar_chart.dart:4:25)

**Comment by roberthartung** [comment]
I will look into this.

**Comment by roberthartung** [comment]
Fixed in 0.1.1.
