### ISSUE TITLE
Incompatible version constraints on polymer 1.0.0-rc.2

### ISSUE THREAD

**Issue by terrywarwar** [roberthartung/google_visualization_api#9]
Incompatible version constraints on polymer:
- app depends on version ^1.0.0-rc.2
- google_charts 0.1.3 depends on version >=0.16.3+1 <0.17.0

Tried adding a depency_override and I'm getting the following issue:
The built-in library 'dart:html' is not available on the stand-alone VM.
'package:polymer/src/template/array_selector.dart': error: line 6 pos 1: library handler failed
import 'dart:html';
^
dart:isolate-patch/isolate_patch.dart 364  Isolate._spawnUri
dart:isolate-patch/isolate_patch.dart 317  Isolate.spawnUri
package:pub/src/dart.dart 221              _isolateBuffer
dart:isolate-patch/isolate_patch.dart 264  _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 148  _RawReceivePortImpl._handleMessage

**Comment by zoechi** [comment]
You can't use Polymer elements built for Polymer.dart <= 0.16.0 with Polymer 1.0.0. I don't know how you can produce the error you mentioned when you run Dart code in the browser, only when you run it on the command line. Polymer can only be run in the browser.

**Comment by terrywarwar** [comment]
The error is from pub serve.  Polymer.dart <= 0.16.0 Transformer was causing the issue.  I removed the dependency and transformer in pubspec.yaml and I was able to build my project.

**Comment by terrywarwar** [comment]
I've changed the examples to work with polymer 1.0.0-rc.2 but can't create a pull request.

**Comment by roberthartung** [comment]
Hi Terry,

thanks for the report. Why exactly can't you create a pull request? Any error messages?

**Comment by terrywarwar** [comment]
Unable to access 403.  I think I should have forked it first.

**Comment by roberthartung** [comment]
Yes. You have to fork the repo, then you can create a pull request or at least I can do the pull request if you can't.

**Comment by terrywarwar** [comment]
ok, will do it now.

**Comment by terrywarwar** [comment]
Fixed in #10.
